---
# roles/sway
user_groups:
  - sudo
  - libvirt

user_dirs:
  - Documents
  - Downloads
  - Pictures
  - Videos
  - Music
  - Desktop
  - Templates
  - Public
  - projects

systemd_user_units:
  - ssh-agent.service
  - nas-backup.timer
  # - nas-prune.timer

systemd_system_units:
  - cups.service

# roles/smb
smb_share: "" # //nas.local/share
smb_mountpoint: "{{ HOME }}/nas"

# roles/vfio
# lspci -nn
vfio_bind_ids:
  - 10de:2684
  - 10de:22ba
