---
# roles/sway
user_groups:
  - sudo
  - libvirt
  - lpadmin

user_dirs:
  - Documents
  - Downloads
  - Pictures
  - Videos
  - Music
  - Desktop
  - Templates
  - Public
  - projects

systemd_user_units:
  - ssh-agent.service
  - syncthing.service
  - emacs.service

systemd_system_units:
  - cups.service

# roles/vfio
# lspci -nn
vfio_bind_ids:
  - 10de:2684
  - 10de:22ba
