all:
  hosts:
    desktop:
      ansible_connection: local

      user_groups:
        - wheel
        - wireshark
        - libvirt
        - docker

      systemd_system_units:
        - cups.service

      systemd_user_units:
        - ssh-agent.service
        - nas-backup.timer
        #- nas-prune.timer
        
      docker_install_compose: true

      smb_share: //nas.local/share
      smb_mount: "{{ home }}/nas"

      br_primary_int: br0
      br_secondary_int: "{{ ansible_default_ipv4.interface }}"
      br_libvirt_net: bridge-network

      # lspci -n
      vfio_bind_ids:
        - 10de:1b80
        - 10de:10f0
      
      passthrough_vms:
        - name: win10-vfio
          memory: 16
          disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
          mouse: /dev/input/by-id/usb-PiMouse_USB_Mouse_Device_fedcba9876543210-event-mouse
          keyboard: /dev/input/by-id/usb-Kinesis_Advantage2_Keyboard_314159265359-if01-event-kbd
          audio_input_device: 'Sound Core3D \[Sound Blaster Recon3D \/ Z-Series\] \(SB1570 SB Audigy Fx\) Analog Stereo:capture_F[LR]'
          audio_output_device: "EasyEffects Sink"
          libvirt_hooks: yes
          # lspci
          pci_devices:
            - "01:00.0"
            - "01:00.1"
            - "03:00.0"

        #- name: win10-dtx
        #  disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
        #  mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
        #  keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
        #  pci_devices:
        #    - "05:00.0"
