all:
  hosts:
    desktop:
      ansible_connection: local

        #user_groups:
        #  - wheel
        #  - wireshark
        #  - libvirt
        #  - docker

        #systemd_system_units:
        #  - cups.service

        #systemd_user_units:
        #  - ssh-agent.service
        #  #- nas-backup.timer
        #  #- nas-prune.timer
        #  
        #docker_install_compose: true

        #smb_share: //nas.local/share
        #smb_mount: "{{ home }}/nas"


        ## lspci -n
        #vfio_bind_ids:
        #  - 10de:2684
        #  - 10de:22ba
