all:
  hosts:
    desktop:
      ansible_connection: local
        #systemd_system_units:
        #  - cups.service

        #smb_share: //nas.local/share

        ## lspci -n
        #vfio_bind_ids:
        #  - 10de:2684
        #  - 10de:22ba
