all:
  hosts:
    desktop:
      ansible_connection: local

      user_groups:
        - wheel
        - wireshark
        - libvirt
        - docker

      systemd_system_units:
        - cups.service

      systemd_user_units:
        - ssh-agent.service
        #- nas-backup.timer
        #- nas-prune.timer
        
      docker_install_compose: true

      smb_share: //nas.local/share
      smb_mount: "{{ home }}/nas"

      br_primary_int: br0
      br_secondary_int: "{{ ansible_default_ipv4.interface }}"
      br_libvirt_net: bridge-network

      # lspci -n
      vfio_bind_ids:
        - 10de:2684
        - 10de:22ba
      
      passthrough_vms:
        - name: win10-vfio
          memory: 16 # GiB
          # total vm vcpus = cores * threads
          cores: 6
          threads: 2

          # cpu pinning (optional)
          # https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#CPU_pinning
          cpu_pins:
            - { vcpu: 0, cpuset: 0 }
            - { vcpu: 1, cpuset: 1 }
            - { vcpu: 2, cpuset: 2 }
            - { vcpu: 3, cpuset: 3 }
            - { vcpu: 4, cpuset: 4 }
            - { vcpu: 5, cpuset: 5 }
            - { vcpu: 6, cpuset: 6 }
            - { vcpu: 7, cpuset: 7 }
            - { vcpu: 8, cpuset: 8 }
            - { vcpu: 9, cpuset: 9 }
            - { vcpu: 10, cpuset: 10 }
            - { vcpu: 11, cpuset: 11 }

          # emulator threads handle interrupt requests and non-blocking processes for virtual machine hardware emulation
          # can be a single value 12 range 12-13 or comma seperated list 12,13 (optional)
          emulator_pins: 12

          # dedicated event loop threads for supported disk devices to perform block I/O requests
          # iothread_pins are only supported for disk_driver: virtio
          # can be a single value 12 range 12-13 or comma seperated list 12,13 (optional)
          #iothread_pins: 13,14,15
          
          disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3

          # virtio or sata (optional) (default: sata)
          disk_driver: sata

          # evdev passthrough (optional)
          # https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_keyboard/mouse_via_Evdev
          mouse: /dev/input/by-id/usb-PiMouse_USB_Mouse_Device_fedcba9876543210-event-mouse
          keyboard: /dev/input/by-id/usb-Kinesis_Advantage2_Keyboard_314159265359-if01-event-kbd

          # audio passthrough via jack and pipewire
          # https://looking-glass.io/wiki/Using_JACK_and_PipeWire
          # list all jack devices: jack_lsp
          audio_input_device: 'Built-in Audio Analog Stereo:capture_F[LR]'
          audio_output_device: "EasyEffects Sink"

          # libvirt cpu optimization hooks (optional)
          libvirt_hooks: yes

          # pci device passthrough (optional)
          # list all pci device ids: lspci
          pci_devices:
            - "01:00.0"
            - "01:00.1"
            - "04:00.0"
