---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include custom playbook config
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/*.config.yml"

  roles:
    - packages
    - home
    - smb
    - bridge-interface
    - vfio
    - vm
