---
- hosts: desktop
  become: yes
  pre_tasks:
    - name: Get pre-task vars
      block:
        - name: Get username var
          command: id -u -n
          register: user
        - set_fact:
            user: "{{ user.stdout }}"

        - name: Get user home dir
          user:
            name: "{{ user }}"
          register: home
        - set_fact:
            home: "{{ home.home }}"

        - name: Get uid var
          command: id -u
          register: uid
        - set_fact:
            uid: "{{ uid.stdout }}"

        - name: Get gid var
          command: id -g
          register: gid 
        - set_fact:
            gid: "{{ gid.stdout }}"
      become: no

    - name: Install playbook dependencies
      dnf:
        name:
          - python3-libselinux
          - python3-lxml
        state: present

  roles:
    - packages
    - geerlingguy.docker
    - home
    - smb
    - bridge-interface
    - vfio
    - passthrough-vm
    - ldnf
