---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include custom playbook config
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - { role: "packages", tags: ["desktop", "music"] }
    - { role: "home", tags: ["desktop", "music"] }
    - { role: "music", tags: "music" }
    - { role: "bridge-interface", tags: "desktop" }
    - { role: "vfio", tags: "desktop" }
    - { role: "vm", tags: "desktop" }
