---
- name: Add Debian non-free repositories
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  become: yes

- name: Load package vars
  include_vars:
    dir: vars

- name: Install Debian packages
  apt:
    name: "{{ debian_packages }}"
    update_cache: yes
    state: present
    install_recommends: no
  become: yes

- name: Install Nvidia drivers
  apt:
    name:
      - nvidia-driver
      - nvidia-settings
    state: present
    install_recommends: no
  become: yes

- name: Enable Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    method: user

- name: Install Flatpak packages
  flatpak:
    name: "{{ flatpak_packages }}"
    state: present
    method: user
