---
- name: Template Debian non-free repositories config
  template:
    src: non-free.list.j2
    dest: /etc/apt/sources.list.d/non-free.list
    mode: '0644'
  become: yes

- name: Load package vars
  include_vars:
    dir: vars

- name: Install Debian packages
  apt:
    name: "{{ debian_packages }}"
    state: present
    install_recommends: no
  become: yes

- name: Enable Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    method: user

- name: Install Flatpak packages
  flatpak:
    name: "{{ flatpak_packages }}"
    state: present
    method: user
