---
# tasks file for home
- name: Add user to groups
  user:
    name: "{{ user }}"
    groups: "{{ user_groups }}"

- name: Create user dirs
  file:
    path: "{{ home }}/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - Documents
    - Downloads
    - Pictures
    - Videos
    - Music
    - Desktop
    - Templates
    - Public
    - projects
    - .local/bin
    - .config/systemd/user
    - .config/nas-backup
    - .config/gtk-3.0
  become: no

- name: Copy kernel modules
  copy:
    src: modules-load.d/
    dest: /etc/modules-load.d/

- name: Reload all kernel modules
  systemd:
    name: systemd-modules-load
    state: restarted

# required by greetd to run user only apps
# e.g. files in "/home/user/.local/bin/"
- name: Copy sh .profile
  copy:
    src: .profile
    dest: "{{ home }}/.profile"
  become: no

- name: Set graphical as default target
  command: systemctl set-default graphical.target

- name: Template greetd configuration
  template:
    src: greetd/config.toml.j2
    dest: /etc/greetd/config.toml

- name: Enable greetd service
  systemd:
    name: greetd
    enabled: yes

- name: Copy nas-backup configs
  copy:
    src: nas-backup/
    dest: "{{ home }}/.config/nas-backup/"
  become: no

- name: Copy systemd user units
  copy:
    src: "systemd/user/"
    dest: "{{ home }}/.config/systemd/user/"
  become: no

- name: Start and enable systemd user units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  loop: "{{ systemd_user_units }}"
  become: no

- name: Start and enable systemd system units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ systemd_system_units }}"

- name: Check if dotfiles repo already exists in home dir
  stat:
    path: "{{ home }}/.git"
  register: dotfiles

- name: Put dotfiles repo in home dir
  when: not dotfiles.stat.exists
  command: "{{ item }}"
  args:
    chdir: "{{ home }}"
  loop:
    - git init
    - git remote add origin https://github.com/basharkey/dotfiles.git
    - git fetch
    - git checkout -t origin/main -f
    - git remote set-url origin git@github.com:basharkey/dotfiles.git
  become: no

- name: Template gtk bookmarks
  template:
    src: gtk-3.0/bookmarks.j2
    dest: "{{ home }}/.config/gtk-3.0/bookmarks"
    force: yes
  become: no

- name: Install wayweather dependencies
  dnf:
    name:
      - python3-pyyaml
      - python3-beautifulsoup4

- name: Install wayweather
  get_url:
    url: https://raw.githubusercontent.com/basharkey/wayweather/main/wayweather.py
    dest: "{{ home }}/.local/bin/wayweather"
    mode: 0755
  become: no

- name: Install spotifyvctl
  get_url:
    url: https://raw.githubusercontent.com/basharkey/spotifyvctl/main/spotifyvctl.py
    dest: "{{ home }}/.local/bin/spotifyvctl"
    mode: 0755
  become: no
