---
- name: Change default target to multi-user.target
  file:
    src: /usr/lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
  become: yes

- name: Create getty service overrides directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'
  become: yes

- name: Template getty service autologin config
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    mode: '0644'
  become: yes

- name: Add line to .profile to automatically run startx on login
  lineinfile:
    path: "{{ HOME }}/.profile"
    line: '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx /etc/X11/Xsession'
    state: present

- name: Stop ssh-agent from being started by default Xsession scripts
  lineinfile:
    path: /etc/X11/Xsession.options
    line: use-ssh-agent
    state: absent
  become: yes

- name: Copy systemd user units
  copy:
    src: systemd-user-units/
    dest: "{{ HOME }}/.config/systemd/user"
    mode: '0644'

- name: Enable systemd user units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop: "{{ systemd_user_units }}"

- name: Start and enable systemd system units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ systemd_system_units }}"
  become: yes

- name: Add user to groups
  user:
    name: "{{ USER }}"
    groups: "{{ user_groups }}"
  become: yes

- name: Create user dirs
  file:
    path: "{{ HOME }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ user_dirs }}"

- name: Create GTK bookmarks dir
  file:
    path: "{{ HOME }}/.config/gtk-3.0"
    state: directory
    mode: '0755'

- name: Template GTK bookmarks
  template:
    src: bookmarks.j2
    dest: "{{ HOME }}/.config/gtk-3.0/bookmarks"
    mode: '0644'

- name: Check if local dotfiles repo already exists
  stat:
    path: "{{ HOME }}/dotfiles"
  register: dotfiles

- name: Clone/update dotfiles repo
  git:
    repo: https://github.com/basharkey/dotfiles.git
    dest: "{{ HOME }}/dotfiles"

- name: Set dotfiles repo remote origin to SSH URI
  command: git remote set-url origin git@github.com:basharkey/dotfiles.git
  args:
    chdir: "{{ HOME }}/dotfiles"

- name: Copy user dotfiles
  when: not dotfiles.stat.isdir is defined
  command: "./install.sh user"
  args:
    chdir: "{{ HOME }}/dotfiles"

- name: Copy user dotfiles with overrides
  when: not dotfiles.stat.isdir is defined and override is defined
  command: "./install.sh user {{ override }}"
  args:
    chdir: "{{ HOME }}/dotfiles"

- name: Copy system dotfiles
  when: not dotfiles.stat.isdir is defined
  command: "./install.sh system"
  args:
    chdir: "{{ HOME }}/dotfiles"
  become: yes

- name: Copy system dotfiles with overrides
  when: not dotfiles.stat.isdir is defined and override is defined
  command: "./install.sh system {{ override }}"
  args:
    chdir: "{{ HOME }}/dotfiles"
  become: yes

- name: Run lm-sensors auto detection for i3block temperature module
  command: sensors-detect --auto
  become: yes

- name: Install custom scripts
  include_tasks:
    file: scripts.yml
