---
- name: "Get {{ device }} pci bus"
  set_fact:
    bus: "0x{{ device | split(':') | first }}"

- name: "Get {{ device }} pci slot"
  set_fact:
    slot: "0x{{ device | regex_search(':(.*)\\.', '\\1') | first }}"

- name: "Get {{ device }} pci function"
  set_fact:
    function: "0x{{ device.split('.')[1] }}"

- name: "Generate {{ device }} pci device definition var"
  set_fact:
    device_template: "{{ lookup('template', 'pci-device.xml.j2') }}"

- name: "Add {{ device }} pci device definition"
  shell: "virsh attach-device --config {{ vm.name }} <(echo '{{ device_template | string }}')"
