---
systemd_user_units:
  - sway.service
  - waybar.service
  - dunst.service
  - wlsunset.service
  - lxpolkit.service
  - easyeffects.service
  - pcmanfm.service
  - nextcloud.service
  - ssh-agent.service
  - nas-backup.timer
  # - nas-prune.timer

user_groups:
  - wheel
  - wireshark
  - libvirt
  - docker

user_dirs:
  - Documents
  - Downloads
  - Pictures
  - Videos
  - Music
  - Desktop
  - Templates
  - Public
  - projects
  - .local/bin
