---
- name: Install sway
  dnf:
    name: sway
    exclude: sway-systemd # Not required when running sway as a systemd user service
    state: present
  become: yes
  
- name: Create global sway config directory
  file:
    path: /etc/sway/config.d
    state: directory
    mode: '0755'
  become: yes

- name: Copy sway systemd user session config
  copy:
    src: systemd-user-session.conf
    dest: /etc/sway/config.d/systemd-user-session.conf
    mode: '0644'
  become: yes

- name: Create getty service overrides directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'
  become: yes
  
- name: Template getty service autologin config
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    mode: '0644'
  become: yes

- name: Copy systemd user units
  copy:
    src: systemd-user-units/
    dest: "{{ HOME }}/.config/systemd/user"
    mode: '0644'

- name: Enable systemd user units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop: "{{ systemd_user_units }}"

- name: Add user to groups
  user:
    name: "{{ USER }}"
    groups: "{{ user_groups }}"
  become: yes

- name: Create user dirs
  file:
    path: "{{ HOME }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ user_dirs }}"

- name: Create GTK bookmarks dir
  file:
    path: "{{ HOME }}/.config/gtk-3.0"
    state: directory
    mode: '0755'

- name: Template GTK bookmarks
  template:
    src: bookmarks.j2
    dest: "{{ HOME }}/.config/gtk-3.0/bookmarks"
    mode: '0644'

- name: Check if local dotfiles repo already exists
  stat:
    path: "{{ HOME }}/dotfiles"
  register: dotfiles

- name: Clone/update dotfiles repo
  git:
    repo: https://github.com/basharkey/dotfiles.git
    dest: "{{ HOME }}/dotfiles"

- name: Set dotfiles repo remote origin to SSH URI
  command: git remote set-url origin git@github.com:basharkey/dotfiles.git
  args:
    chdir: "{{ HOME/dotfiles }}"

- name: Copy dotfiles
  when: dotfiles.stat.isdir is defined and dotfiles.stat.isdir
  block:
    - name: Copy user dotfiles
      command: "cp -rT {{ HOME }}/dotfiles/user {{ HOME }}"

    - name: Copy system dotfiles
      command: "cp -rT {{ HOME }}/dotfiles/system /"
      become: yes
