---
- name: Install sway
  dnf:
    name: sway
    exclude: sway-systemd # Not required when running sway as a systemd user service
    state: present
  become: yes
  
- name: Create global sway config directory
  file:
    path: /etc/sway/config.d
    state: directory
    mode: '0755'
  become: yes

- name: Copy sway systemd user session config
  copy:
    src: systemd-user-session.conf
    dest: /etc/sway/config.d/systemd-user-session.conf
    mode: '0644'
  become: yes

- name: Create getty service overrides directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'
  become: yes
  
- name: Template getty service autologin config
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    mode: '0644'
  become: yes

- name: Copy systemd user units
  copy:
    src: systemd-user-units/
    dest: "{{ HOME }}/.config/systemd/user"
    mode: '0644'
  become: no

- name: Enable systemd user units
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop: "{{ systemd_user_units }}"
