---
- name: Grub enable iommu
  block:
    - name: Check if iommu enabled in grub config
      command: egrep "(amd|intel)_iommu=on" /etc/default/grub
  rescue:
    - name: Grub enable amd iommu
      command: sed -i 's|GRUB_CMDLINE_LINUX="[^"]*|& amd_iommu=on|g' /etc/default/grub
      when: ansible_processor[1] == "AuthenticAMD"
    
    - name: Grub enable intel iommu
      command: sed -i 's|GRUB_CMDLINE_LINUX="[^"]*|& intel_iommu=on|g' /etc/default/grub
      when: ansible_processor[1] == "GenuineIntel"
    
    - name: Write grub config
      command: grub2-mkconfig > /etc/grub2-efi.cfg 

- name: Template qemu.conf
  template:
    src: qemu.conf.j2
    dest: /etc/libvirt/qemu.conf
    mode: 0644

- name: Install qemu jack dependencies
  dnf:
    name:
      - pipewire-jack-audio-connection-kit
      - qemu-audio-jack
    state: present

- name: Install libvirt-jack-socket selinux module
  block: 
    - name: Check if libvirt-jack-socket selinux module is installed
      shell: semodule -l | grep libvirt-jack-socket
  rescue:
    - name: Copy libvirt-jack-socket selinux type enforcement file
      copy:
        src: libvirt-jack-socket.te
        dest: /tmp/libvirt-jack-socket.te

    - name: Compile libvirt-jack-socket selinux module file
      command: checkmodule -M -m -o libvirt-jack-socket.mod libvirt-jack-socket.te
      args:
        chdir: /tmp

    - name: Build libvirt-jack-socket selinux policy package
      command: semodule_package -o libvirt-jack-socket.pp -m libvirt-jack-socket.mod
      args:
        chdir: /tmp

    - name: Install libvirt-jack-socket selinux policy package
      command: semodule -i libvirt-jack-socket.pp
      args:
        chdir: /tmp

- name: Start and enable virtqemud
  systemd:
    name: virtqemud
    state: started
    enabled: yes

- name: Copy vfio modules config
  copy:
    src: vfio-modules.conf
    dest: /etc/modules-load.d/vfio.conf

- name: Template vfio module options config
  template:
    src: vfio-options.conf.j2
    dest: /etc/modprobe.d/vfio.conf
    mode: 0644

- name: Update initramfs
  command: dracut -fv

- name: Install virtio-win repo
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
    dest: /etc/yum.repos.d/virtio-win.repo

- name: Install virtio-win drivers iso
  # /usr/share/virtio-win/virtio-win.iso
  dnf:
    name: virtio-win
    state: present
